// generated from ontology (SHACL) - do not edit
import type { Schema } from "../types";

export const CONTRACT_SCHEMA: Schema = {
  $id: 'https://schemas.agentictrust.io/contract-node/v1.1.1/schema.json',
  source: 'https://schemas.agentictrust.io/',
  title: 'Contract',
  version: '1.1.1',
  description: 'Smart contract metadata profile following Enscribe smart contract metadata format.',
  type: 'object' as const,
  properties: {
    class: { type: 'string', description: 'High-level identifier of this node type', default: 'Contract' },
    alias: { type: 'string', description: 'Human-readable contract alias (ENSIP-18 alias)' },
    description: { type: 'string', description: 'Short description of the contract purpose (ENSIP-18 description)' },
    avatar: { type: 'string', description: 'Avatar URI for the contract profile (ENSIP-12 avatar)' },
    category: { type: 'string', description: 'Contract category (e.g., defi, gaming, dao, utility, proxy, factory)' },
    license: { type: 'string', description: 'Official software license identifier for the source code' },
    docs: { type: 'string', description: 'Primary documentation URL for developers and users', format: 'uri' },
    'compiled-metadata': { type: 'string', description: 'A URI to a contract metadata file as generated by a Solidity or Vyper compiler' },
    audits: { type: 'string', description: 'JSON array of third-party audit reports' },
  },
  required: ['class'],
  recommended: ['alias', 'description']
};
